# Generated by Django 4.1.4 on 2022-12-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
